---
R1:
    username: cisco
    password: cisco
    hostname: "192.168.2.244"
    groups:
        - cisco_group

R2:
    username: cisco
    password: cisco
    hostname: "192.168.2.246"
    groups:
        - cisco_group

R3:
    username: cisco
    password: cisco
    hostname: "192.168.2.245"
    groups:
        - cisco_group